// Licensed to the.NET Foundation under one or more agreements.
// The.NET Foundation licenses this file to you under the MIT license.

using ExpertBridge.Core.Entities.Posts;
using ExpertBridge.Core.Entities.Tags;

namespace ExpertBridge.Core.Entities.ManyToManyRelationships.PostTags;

/// <summary>
/// Represents a many-to-many relationship between posts and tags.
/// </summary>
/// <remarks>
/// Post tags are automatically generated by AI (Groq API) to categorize content and enable semantic search.
/// Tags support both English and Arabic for multilingual discoverability. The tagging process is triggered
/// asynchronously via RabbitMQ/MassTransit message pipeline.
/// </remarks>
public class PostTag
{
    /// <summary>
    /// Gets or sets the unique identifier of the post.
    /// </summary>
    public string PostId { get; set; }

    /// <summary>
    /// Gets or sets the unique identifier of the tag.
    /// </summary>
    public string TagId { get; set; }

    // Navigation properties
    /// <summary>
    /// Gets or sets the post being tagged.
    /// </summary>
    public Post Post { get; set; }

    /// <summary>
    /// Gets or sets the tag applied to the post.
    /// </summary>
    public Tag Tag { get; set; }
}
