// Licensed to the.NET Foundation under one or more agreements.
// The.NET Foundation licenses this file to you under the MIT license.

namespace ExpertBridge.Core.EntityConfiguration;

/// <summary>
/// Defines PostgreSQL column type constants for Entity Framework Core configuration.
/// </summary>
/// <remarks>
/// Used in entity configurations to specify pgvector column types for storing embeddings.
/// These embeddings enable semantic similarity search using cosine distance or other vector operations.
/// </remarks>
public static class ColumnTypes
{
    /// <summary>
    /// PostgreSQL pgvector column type for 1024-dimensional vector embeddings.
    /// </summary>
    /// <remarks>
    /// Used for storing embeddings generated by models like Ollama for semantic search and similarity matching.
    /// </remarks>
    public const string Vector1024 = "vector(1024)";
}
