// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

using ExpertBridge.Core.Entities.JobPostings;
using ExpertBridge.Core.Entities.Tags;

namespace ExpertBridge.Core.Entities.ManyToManyRelationships.JobPostingTags;

/// <summary>
/// Represents a many-to-many relationship between job postings and tags.
/// </summary>
/// <remarks>
/// Job posting tags are automatically generated by AI (Groq API) to categorize job opportunities
/// and improve discoverability through semantic search. Tags are multilingual with English and Arabic names.
/// </remarks>
public class JobPostingTag
{
    /// <summary>
    /// Gets or sets the unique identifier of the job posting.
    /// </summary>
    public string JobPostingId { get; set; }

    /// <summary>
    /// Gets or sets the unique identifier of the tag.
    /// </summary>
    public string TagId { get; set; }

    // Navigation properties
    /// <summary>
    /// Gets or sets the job posting being tagged.
    /// </summary>
    public JobPosting JobPosting { get; set; }

    /// <summary>
    /// Gets or sets the tag applied to the job posting.
    /// </summary>
    public Tag Tag { get; set; }
}
