// Licensed to the.NET Foundation under one or more agreements.
// The.NET Foundation licenses this file to you under the MIT license.

namespace ExpertBridge.Core.Responses;

/// <summary>
/// Represents the response from the AI content moderation service.
/// </summary>
/// <remarks>
/// This DTO contains toxicity scores across multiple categories for detecting inappropriate content.
/// Scores are generated by AI models analyzing text for harmful language.
/// Used to implement the <see cref="Interfaces.ISafeContent"/> interface on posts and comments.
/// </remarks>
public class InappropriateLanguageDetectionResponse
{
    /// <summary>
    /// Gets or sets the general toxicity score of the content.
    /// </summary>
    /// <remarks>
    /// Values range from 0.0 (safe) to 1.0 (highly toxic).
    /// </remarks>
    public double Toxicity { get; set; }

    /// <summary>
    /// Gets or sets the severe toxicity score of the content.
    /// </summary>
    /// <remarks>
    /// Values range from 0.0 (safe) to 1.0 (extremely toxic).
    /// This indicates more serious forms of harmful content.
    /// </remarks>
    public double SevereToxicity { get; set; }

    /// <summary>
    /// Gets or sets the obscenity score of the content.
    /// </summary>
    /// <remarks>
    /// Values range from 0.0 (clean) to 1.0 (highly obscene).
    /// Detects profanity and vulgar language.
    /// </remarks>
    public double Obscene { get; set; }

    /// <summary>
    /// Gets or sets the threat score of the content.
    /// </summary>
    /// <remarks>
    /// Values range from 0.0 (no threat) to 1.0 (explicit threat).
    /// Identifies threatening language or intimidation.
    /// </remarks>
    public double Threat { get; set; }

    /// <summary>
    /// Gets or sets the insult score of the content.
    /// </summary>
    /// <remarks>
    /// Values range from 0.0 (respectful) to 1.0 (highly insulting).
    /// Detects insulting or degrading language.
    /// </remarks>
    public double Insult { get; set; }

    /// <summary>
    /// Gets or sets the identity attack score of the content.
    /// </summary>
    /// <remarks>
    /// Values range from 0.0 (safe) to 1.0 (severe identity attack).
    /// Identifies hateful language targeting protected groups based on identity characteristics.
    /// </remarks>
    public double IdentityAttack { get; set; }

    /// <summary>
    /// Gets or sets the sexual explicitness score of the content.
    /// </summary>
    /// <remarks>
    /// Values range from 0.0 (appropriate) to 1.0 (sexually explicit).
    /// Detects sexually explicit or suggestive content.
    /// </remarks>
    public double SexualExplicit { get; set; }
}
