// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

namespace ExpertBridge.Core.Responses;

/// <summary>
/// Represents the response from the AI post categorization service.
/// </summary>
/// <remarks>
/// This DTO contains the detected language and AI-generated tags for a post or job posting.
/// Tags are generated by analyzing content using LLM services (Groq/Ollama).
/// </remarks>
public class PostCategorizerResponse
{
    /// <summary>
    /// Gets or sets the detected language of the content.
    /// </summary>
    /// <remarks>
    /// Supports multilingual content with values like "en" for English, "ar" for Arabic, etc.
    /// </remarks>
    public string Language { get; set; }

    /// <summary>
    /// Gets or sets the collection of AI-generated tags categorizing the content.
    /// </summary>
    public List<CategorizerTagResponse> Tags { get; set; }
}

/// <summary>
/// Represents a tag generated by the AI categorization service.
/// </summary>
/// <remarks>
/// Tags include multilingual names and descriptions to support internationalization.
/// </remarks>
public class CategorizerTagResponse
{
    /// <summary>
    /// Gets or sets the Arabic name of the tag.
    /// </summary>
    public string ArabicName { get; set; }

    /// <summary>
    /// Gets or sets the English name of the tag.
    /// </summary>
    public string EnglishName { get; set; }

    /// <summary>
    /// Gets or sets the description of the tag.
    /// </summary>
    public string Description { get; set; }
}
