// Licensed to the.NET Foundation under one or more agreements.
// The.NET Foundation licenses this file to you under the MIT license.

namespace ExpertBridge.Core.Responses;

/// <summary>
/// Represents the response DTO for tag information.
/// </summary>
/// <remarks>
/// Tags are used to categorize posts and job postings, supporting multilingual names (English and Arabic).
/// Tags are automatically generated by AI analysis of content.
/// </remarks>
public class TagResponse
{
    /// <summary>
    /// Gets or sets the unique identifier of the tag.
    /// </summary>
    public string TagId { get; set; } = null!;

    /// <summary>
    /// Gets or sets the English name of the tag.
    /// </summary>
    public string EnglishName { get; set; } = null!;

    /// <summary>
    /// Gets or sets the Arabic name of the tag.
    /// </summary>
    public string ArabicName { get; set; } = null!;

    /// <summary>
    /// Gets or sets the description of the tag.
    /// </summary>
    public string Description { get; set; } = null!;
}
