services:
  postgres:
    image: pgvector/pgvector:pg17
    container_name: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
       - target: 5432
         published: 5432
         protocol: tcp
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 3s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
    networks:
      - postgresql
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin@admin
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    ports:
       - target: 80
         published: 5050
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - postgresql
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M

volumes:
  postgres_data:
    name: postgres_data
    driver: local
  pgadmin_data:
    name: pgadmin_data
    driver: local

networks:
  postgresql:
    name: postgresql
    driver: bridge
