// <auto-generated />
using System;
using ExpertBridge.Data.DatabaseContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ExpertBridge.Data.Migrations
{
    [DbContext(typeof(ExpertBridgeDbContext))]
    [Migration("20250222144618_UpdateFirebaseIdProbNameToProviderId")]
    partial class UpdateFirebaseIdProbNameToProviderId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ExpertBridge.Core.Entities.Area.Area", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("Governorate")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ProfileId")
                        .IsRequired()
                        .HasColumnType("character varying(450)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.ToTable("Areas");
                });

            modelBuilder.Entity("ExpertBridge.Core.Entities.Badge.Badge", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Badges");
                });

            modelBuilder.Entity("ExpertBridge.Core.Entities.Chat.Chat", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Chats");
                });

            modelBuilder.Entity("ExpertBridge.Core.Entities.Chat.ChatParticipant.ChatParticipant", b =>
                {
                    b.Property<string>("ChatId")
                        .HasColumnType("character varying(450)");

                    b.Property<string>("ProfileId")
                        .HasColumnType("character varying(450)");

                    b.HasKey("ChatId", "ProfileId");

                    b.HasIndex("ProfileId")
                        .IsUnique();

                    b.ToTable("ChatParticipants");
                });

            modelBuilder.Entity("ExpertBridge.Core.Entities.Comment.Comment", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("AuthorId")
                        .IsRequired()
                        .HasColumnType("character varying(450)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastModified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ParentId")
                        .HasColumnType("character varying(450)");

                    b.Property<string>("PostId")
                        .HasColumnType("character varying(450)");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("ParentId");

                    b.HasIndex("PostId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("ExpertBridge.Core.Entities.Job.Job", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<double>("ActualCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("double precision");

                    b.Property<string>("AuthorId")
                        .IsRequired()
                        .HasColumnType("character varying(450)");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("JobPostingId")
                        .HasColumnType("character varying(450)");

                    b.Property<string>("JobStatusId")
                        .IsRequired()
                        .HasColumnType("character varying(450)");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WorkerId")
                        .IsRequired()
                        .HasColumnType("character varying(450)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("JobPostingId")
                        .IsUnique();

                    b.HasIndex("JobStatusId");

                    b.HasIndex("WorkerId");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("ExpertBridge.Core.Entities.Job.JobReview.JobReview", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("character varying(450)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("JobId")
                        .IsRequired()
                        .HasColumnType("character varying(450)");

                    b.Property<DateTime?>("LastModified")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<string>("WorkerId")
                        .IsRequired()
                        .HasColumnType("character varying(450)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("JobId")
                        .IsUnique();

                    b.HasIndex("WorkerId");

                    b.ToTable("JobReviews");
                });

            modelBuilder.Entity("ExpertBridge.Core.Entities.Job.JobStatus.JobStatus", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.ToTable("JobStatuses");
                });

            modelBuilder.Entity("ExpertBridge.Core.Entities.JobCategory.JobCategory", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("JobCategories");
                });

            modelBuilder.Entity("ExpertBridge.Core.Entities.JobPosting.JobPosting", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("AreaId")
                        .IsRequired()
                        .HasColumnType("character varying(450)");

                    b.Property<string>("AuthorId")
                        .IsRequired()
                        .HasColumnType("character varying(450)");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasColumnType("character varying(450)");

                    b.Property<double>("Cost")
                        .HasPrecision(18, 2)
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.HasIndex("AuthorId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Title");

                    b.ToTable("JobPostings");
                });

            modelBuilder.Entity("ExpertBridge.Core.Entities.ManyToManyRelationships.PostTag.PostTag", b =>
                {
                    b.Property<string>("PostId")
                        .HasColumnType("character varying(450)");

                    b.Property<string>("TagId")
                        .HasColumnType("character varying(450)");

                    b.HasKey("PostId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("PostTags");
                });

            modelBuilder.Entity("ExpertBridge.Core.Entities.ManyToManyRelationships.ProfileBadge.ProfileBadge", b =>
                {
                    b.Property<string>("ProfileId")
                        .HasColumnType("character varying(450)");

                    b.Property<string>("BadgeId")
                        .HasColumnType("character varying(450)");

                    b.HasKey("ProfileId", "BadgeId");

                    b.HasIndex("BadgeId");

                    b.ToTable("ProfileBadges");
                });

            modelBuilder.Entity("ExpertBridge.Core.Entities.ManyToManyRelationships.ProfileSkill.ProfileSkill", b =>
                {
                    b.Property<string>("ProfileId")
                        .HasColumnType("character varying(450)");

                    b.Property<string>("SkillId")
                        .HasColumnType("character varying(450)");

                    b.HasKey("ProfileId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("ProfileSkills");
                });

            modelBuilder.Entity("ExpertBridge.Core.Entities.ManyToManyRelationships.ProfileTag.ProfileTag", b =>
                {
                    b.Property<string>("ProfileId")
                        .HasColumnType("character varying(450)");

                    b.Property<string>("TagId")
                        .HasColumnType("character varying(450)");

                    b.HasKey("ProfileId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("ProfileTags");
                });

            modelBuilder.Entity("ExpertBridge.Core.Entities.Media.ChatMedia.ChatMedia", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("ChatId")
                        .IsRequired()
                        .HasColumnType("character varying(450)");

                    b.Property<string>("MediaId")
                        .IsRequired()
                        .HasColumnType("character varying(450)");

                    b.HasKey("Id");

                    b.HasIndex("ChatId");

                    b.HasIndex("MediaId")
                        .IsUnique();

                    b.ToTable("ChatMedias");
                });

            modelBuilder.Entity("ExpertBridge.Core.Entities.Media.CommentMedia.CommentMedia", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("CommentId")
                        .IsRequired()
                        .HasColumnType("character varying(450)");

                    b.Property<string>("MediaId")
                        .IsRequired()
                        .HasColumnType("character varying(450)");

                    b.HasKey("Id");

                    b.HasIndex("CommentId")
                        .IsUnique();

                    b.HasIndex("MediaId")
                        .IsUnique();

                    b.ToTable("CommentMedias");
                });

            modelBuilder.Entity("ExpertBridge.Core.Entities.Media.JobPostingMedia.JobPostingMedia", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("JobPostingId")
                        .IsRequired()
                        .HasColumnType("character varying(450)");

                    b.Property<string>("MediaId")
                        .IsRequired()
                        .HasColumnType("character varying(450)");

                    b.HasKey("Id");

                    b.HasIndex("JobPostingId");

                    b.HasIndex("MediaId")
                        .IsUnique();

                    b.ToTable("JobPostingMedias");
                });

            modelBuilder.Entity("ExpertBridge.Core.Entities.Media.Media", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastModified")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MediaTypeId")
                        .IsRequired()
                        .HasColumnType("character varying(450)");

                    b.Property<string>("MediaUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("MediaTypeId");

                    b.HasIndex("MediaUrl")
                        .IsUnique();

                    b.ToTable("Media");
                });

            modelBuilder.Entity("ExpertBridge.Core.Entities.Media.MediaType.MediaType", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.ToTable("MediaTypes");
                });

            modelBuilder.Entity("ExpertBridge.Core.Entities.Media.PostMedia.PostMedia", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("MediaId")
                        .IsRequired()
                        .HasColumnType("character varying(450)");

                    b.Property<string>("PostId")
                        .IsRequired()
                        .HasColumnType("character varying(450)");

                    b.HasKey("Id");

                    b.HasIndex("MediaId")
                        .IsUnique();

                    b.HasIndex("PostId");

                    b.ToTable("PostMedias");
                });

            modelBuilder.Entity("ExpertBridge.Core.Entities.Media.ProfileExperienceMedia.ProfileExperienceMedia", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("MediaId")
                        .IsRequired()
                        .HasColumnType("character varying(450)");

                    b.Property<string>("ProfileExperienceId")
                        .IsRequired()
                        .HasColumnType("character varying(450)");

                    b.HasKey("Id");

                    b.HasIndex("MediaId")
                        .IsUnique();

                    b.HasIndex("ProfileExperienceId");

                    b.ToTable("ProfileExperienceMedias");
                });

            modelBuilder.Entity("ExpertBridge.Core.Entities.Media.ProfileMedia.ProfileMedia", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("MediaId")
                        .IsRequired()
                        .HasColumnType("character varying(450)");

                    b.Property<string>("ProfileId")
                        .IsRequired()
                        .HasColumnType("character varying(450)");

                    b.HasKey("Id");

                    b.HasIndex("MediaId")
                        .IsUnique();

                    b.HasIndex("ProfileId");

                    b.ToTable("ProfileMedias");
                });

            modelBuilder.Entity("ExpertBridge.Core.Entities.Post.Post", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("AuthorId")
                        .IsRequired()
                        .HasColumnType("character varying(450)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastModified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("Title");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("ExpertBridge.Core.Entities.Profile.Profile", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ProfilePictureUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<int>("RatingCount")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("character varying(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("ExpertBridge.Core.Entities.ProfileExperience.ProfileExperience", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("EndDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ProfileId")
                        .IsRequired()
                        .HasColumnType("character varying(450)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.ToTable("ProfileExperiences");
                });

            modelBuilder.Entity("ExpertBridge.Core.Entities.Skill.Skill", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("ExpertBridge.Core.Entities.Tags.Tag", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("ExpertBridge.Core.Entities.User.User", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsBanned")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOnBoarded")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("ProviderId")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ExpertBridge.Core.Entities.Votes.CommentVote.CommentVote", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("CommentId")
                        .IsRequired()
                        .HasColumnType("character varying(450)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsUpvote")
                        .HasColumnType("boolean");

                    b.Property<string>("ProfileId")
                        .IsRequired()
                        .HasColumnType("character varying(450)");

                    b.HasKey("Id");

                    b.HasIndex("CommentId");

                    b.HasIndex("ProfileId", "CommentId")
                        .IsUnique();

                    b.ToTable("CommentVotes");
                });

            modelBuilder.Entity("ExpertBridge.Core.Entities.Votes.PostVote.PostVote", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsUpvote")
                        .HasColumnType("boolean");

                    b.Property<string>("PostId")
                        .IsRequired()
                        .HasColumnType("character varying(450)");

                    b.Property<string>("ProfileId")
                        .IsRequired()
                        .HasColumnType("character varying(450)");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("ProfileId", "PostId")
                        .IsUnique();

                    b.ToTable("PostVotes");
                });

            modelBuilder.Entity("ExpertBridge.Core.Entities.Area.Area", b =>
                {
                    b.HasOne("ExpertBridge.Core.Entities.Profile.Profile", "Profile")
                        .WithMany("Areas")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("ExpertBridge.Core.Entities.Chat.ChatParticipant.ChatParticipant", b =>
                {
                    b.HasOne("ExpertBridge.Core.Entities.Chat.Chat", "Chat")
                        .WithMany("Participants")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExpertBridge.Core.Entities.Profile.Profile", "Profile")
                        .WithOne("ChatParticipant")
                        .HasForeignKey("ExpertBridge.Core.Entities.Chat.ChatParticipant.ChatParticipant", "ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chat");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("ExpertBridge.Core.Entities.Comment.Comment", b =>
                {
                    b.HasOne("ExpertBridge.Core.Entities.Profile.Profile", "Author")
                        .WithMany("Comments")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExpertBridge.Core.Entities.Comment.Comment", "Parent")
                        .WithMany("Replies")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ExpertBridge.Core.Entities.Post.Post", null)
                        .WithMany("Comments")
                        .HasForeignKey("PostId");

                    b.Navigation("Author");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("ExpertBridge.Core.Entities.Job.Job", b =>
                {
                    b.HasOne("ExpertBridge.Core.Entities.Profile.Profile", "Author")
                        .WithMany("JobsAsAuthor")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExpertBridge.Core.Entities.JobPosting.JobPosting", "JobPosting")
                        .WithOne("Job")
                        .HasForeignKey("ExpertBridge.Core.Entities.Job.Job", "JobPostingId");

                    b.HasOne("ExpertBridge.Core.Entities.Job.JobStatus.JobStatus", "Status")
                        .WithMany("Jobs")
                        .HasForeignKey("JobStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExpertBridge.Core.Entities.Profile.Profile", "Worker")
                        .WithMany("JobsAsWorker")
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("JobPosting");

                    b.Navigation("Status");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("ExpertBridge.Core.Entities.Job.JobReview.JobReview", b =>
                {
                    b.HasOne("ExpertBridge.Core.Entities.Profile.Profile", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExpertBridge.Core.Entities.Job.Job", "Job")
                        .WithOne("Review")
                        .HasForeignKey("ExpertBridge.Core.Entities.Job.JobReview.JobReview", "JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExpertBridge.Core.Entities.Profile.Profile", "Worker")
                        .WithMany()
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Job");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("ExpertBridge.Core.Entities.JobPosting.JobPosting", b =>
                {
                    b.HasOne("ExpertBridge.Core.Entities.Area.Area", "Area")
                        .WithMany("JobPostings")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExpertBridge.Core.Entities.Profile.Profile", "Author")
                        .WithMany("JobPostings")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExpertBridge.Core.Entities.JobCategory.JobCategory", "Category")
                        .WithMany("JobPostings")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");

                    b.Navigation("Author");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ExpertBridge.Core.Entities.ManyToManyRelationships.PostTag.PostTag", b =>
                {
                    b.HasOne("ExpertBridge.Core.Entities.Post.Post", "Post")
                        .WithMany("PostTags")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExpertBridge.Core.Entities.Tags.Tag", "Tag")
                        .WithMany("PostTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("ExpertBridge.Core.Entities.ManyToManyRelationships.ProfileBadge.ProfileBadge", b =>
                {
                    b.HasOne("ExpertBridge.Core.Entities.Badge.Badge", "Badge")
                        .WithMany("ProfileBadges")
                        .HasForeignKey("BadgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExpertBridge.Core.Entities.Profile.Profile", "Profile")
                        .WithMany("ProfileBadges")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Badge");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("ExpertBridge.Core.Entities.ManyToManyRelationships.ProfileSkill.ProfileSkill", b =>
                {
                    b.HasOne("ExpertBridge.Core.Entities.Profile.Profile", "Profile")
                        .WithMany("ProfileSkills")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExpertBridge.Core.Entities.Skill.Skill", "Skill")
                        .WithMany("ProfileSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("ExpertBridge.Core.Entities.ManyToManyRelationships.ProfileTag.ProfileTag", b =>
                {
                    b.HasOne("ExpertBridge.Core.Entities.Profile.Profile", "Profile")
                        .WithMany("ProfileTags")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExpertBridge.Core.Entities.Tags.Tag", "Tag")
                        .WithMany("ProfileTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("ExpertBridge.Core.Entities.Media.ChatMedia.ChatMedia", b =>
                {
                    b.HasOne("ExpertBridge.Core.Entities.Chat.Chat", "Chat")
                        .WithMany("Medias")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExpertBridge.Core.Entities.Media.Media", "Media")
                        .WithOne("Chat")
                        .HasForeignKey("ExpertBridge.Core.Entities.Media.ChatMedia.ChatMedia", "MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chat");

                    b.Navigation("Media");
                });

            modelBuilder.Entity("ExpertBridge.Core.Entities.Media.CommentMedia.CommentMedia", b =>
                {
                    b.HasOne("ExpertBridge.Core.Entities.Comment.Comment", "Comment")
                        .WithOne("Media")
                        .HasForeignKey("ExpertBridge.Core.Entities.Media.CommentMedia.CommentMedia", "CommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExpertBridge.Core.Entities.Media.Media", "Media")
                        .WithOne("Comment")
                        .HasForeignKey("ExpertBridge.Core.Entities.Media.CommentMedia.CommentMedia", "MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comment");

                    b.Navigation("Media");
                });

            modelBuilder.Entity("ExpertBridge.Core.Entities.Media.JobPostingMedia.JobPostingMedia", b =>
                {
                    b.HasOne("ExpertBridge.Core.Entities.JobPosting.JobPosting", "JobPosting")
                        .WithMany("Medias")
                        .HasForeignKey("JobPostingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExpertBridge.Core.Entities.Media.Media", "Media")
                        .WithOne("JobPosting")
                        .HasForeignKey("ExpertBridge.Core.Entities.Media.JobPostingMedia.JobPostingMedia", "MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobPosting");

                    b.Navigation("Media");
                });

            modelBuilder.Entity("ExpertBridge.Core.Entities.Media.Media", b =>
                {
                    b.HasOne("ExpertBridge.Core.Entities.Media.MediaType.MediaType", "MediaType")
                        .WithMany("Medias")
                        .HasForeignKey("MediaTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaType");
                });

            modelBuilder.Entity("ExpertBridge.Core.Entities.Media.PostMedia.PostMedia", b =>
                {
                    b.HasOne("ExpertBridge.Core.Entities.Media.Media", "Media")
                        .WithOne("Post")
                        .HasForeignKey("ExpertBridge.Core.Entities.Media.PostMedia.PostMedia", "MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExpertBridge.Core.Entities.Post.Post", "Post")
                        .WithMany("Medias")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Media");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("ExpertBridge.Core.Entities.Media.ProfileExperienceMedia.ProfileExperienceMedia", b =>
                {
                    b.HasOne("ExpertBridge.Core.Entities.Media.Media", "Media")
                        .WithOne("ProfileExperience")
                        .HasForeignKey("ExpertBridge.Core.Entities.Media.ProfileExperienceMedia.ProfileExperienceMedia", "MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExpertBridge.Core.Entities.ProfileExperience.ProfileExperience", "ProfileExperience")
                        .WithMany("Medias")
                        .HasForeignKey("ProfileExperienceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Media");

                    b.Navigation("ProfileExperience");
                });

            modelBuilder.Entity("ExpertBridge.Core.Entities.Media.ProfileMedia.ProfileMedia", b =>
                {
                    b.HasOne("ExpertBridge.Core.Entities.Media.Media", "Media")
                        .WithOne("Profile")
                        .HasForeignKey("ExpertBridge.Core.Entities.Media.ProfileMedia.ProfileMedia", "MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExpertBridge.Core.Entities.Profile.Profile", "Profile")
                        .WithMany("Medias")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Media");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("ExpertBridge.Core.Entities.Post.Post", b =>
                {
                    b.HasOne("ExpertBridge.Core.Entities.Profile.Profile", "Author")
                        .WithMany("Posts")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("ExpertBridge.Core.Entities.Profile.Profile", b =>
                {
                    b.HasOne("ExpertBridge.Core.Entities.User.User", "User")
                        .WithOne("Profile")
                        .HasForeignKey("ExpertBridge.Core.Entities.Profile.Profile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ExpertBridge.Core.Entities.ProfileExperience.ProfileExperience", b =>
                {
                    b.HasOne("ExpertBridge.Core.Entities.Profile.Profile", "Profile")
                        .WithMany("Experiences")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("ExpertBridge.Core.Entities.Votes.CommentVote.CommentVote", b =>
                {
                    b.HasOne("ExpertBridge.Core.Entities.Comment.Comment", "Comment")
                        .WithMany("Votes")
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExpertBridge.Core.Entities.Profile.Profile", "Profile")
                        .WithMany("CommentVotes")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comment");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("ExpertBridge.Core.Entities.Votes.PostVote.PostVote", b =>
                {
                    b.HasOne("ExpertBridge.Core.Entities.Post.Post", "Post")
                        .WithMany("Votes")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExpertBridge.Core.Entities.Profile.Profile", "Profile")
                        .WithMany("PostVotes")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("ExpertBridge.Core.Entities.Area.Area", b =>
                {
                    b.Navigation("JobPostings");
                });

            modelBuilder.Entity("ExpertBridge.Core.Entities.Badge.Badge", b =>
                {
                    b.Navigation("ProfileBadges");
                });

            modelBuilder.Entity("ExpertBridge.Core.Entities.Chat.Chat", b =>
                {
                    b.Navigation("Medias");

                    b.Navigation("Participants");
                });

            modelBuilder.Entity("ExpertBridge.Core.Entities.Comment.Comment", b =>
                {
                    b.Navigation("Media")
                        .IsRequired();

                    b.Navigation("Replies");

                    b.Navigation("Votes");
                });

            modelBuilder.Entity("ExpertBridge.Core.Entities.Job.Job", b =>
                {
                    b.Navigation("Review")
                        .IsRequired();
                });

            modelBuilder.Entity("ExpertBridge.Core.Entities.Job.JobStatus.JobStatus", b =>
                {
                    b.Navigation("Jobs");
                });

            modelBuilder.Entity("ExpertBridge.Core.Entities.JobCategory.JobCategory", b =>
                {
                    b.Navigation("JobPostings");
                });

            modelBuilder.Entity("ExpertBridge.Core.Entities.JobPosting.JobPosting", b =>
                {
                    b.Navigation("Job");

                    b.Navigation("Medias");
                });

            modelBuilder.Entity("ExpertBridge.Core.Entities.Media.Media", b =>
                {
                    b.Navigation("Chat")
                        .IsRequired();

                    b.Navigation("Comment")
                        .IsRequired();

                    b.Navigation("JobPosting")
                        .IsRequired();

                    b.Navigation("Post")
                        .IsRequired();

                    b.Navigation("Profile")
                        .IsRequired();

                    b.Navigation("ProfileExperience")
                        .IsRequired();
                });

            modelBuilder.Entity("ExpertBridge.Core.Entities.Media.MediaType.MediaType", b =>
                {
                    b.Navigation("Medias");
                });

            modelBuilder.Entity("ExpertBridge.Core.Entities.Post.Post", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Medias");

                    b.Navigation("PostTags");

                    b.Navigation("Votes");
                });

            modelBuilder.Entity("ExpertBridge.Core.Entities.Profile.Profile", b =>
                {
                    b.Navigation("Areas");

                    b.Navigation("ChatParticipant")
                        .IsRequired();

                    b.Navigation("CommentVotes");

                    b.Navigation("Comments");

                    b.Navigation("Experiences");

                    b.Navigation("JobPostings");

                    b.Navigation("JobsAsAuthor");

                    b.Navigation("JobsAsWorker");

                    b.Navigation("Medias");

                    b.Navigation("PostVotes");

                    b.Navigation("Posts");

                    b.Navigation("ProfileBadges");

                    b.Navigation("ProfileSkills");

                    b.Navigation("ProfileTags");
                });

            modelBuilder.Entity("ExpertBridge.Core.Entities.ProfileExperience.ProfileExperience", b =>
                {
                    b.Navigation("Medias");
                });

            modelBuilder.Entity("ExpertBridge.Core.Entities.Skill.Skill", b =>
                {
                    b.Navigation("ProfileSkills");
                });

            modelBuilder.Entity("ExpertBridge.Core.Entities.Tags.Tag", b =>
                {
                    b.Navigation("PostTags");

                    b.Navigation("ProfileTags");
                });

            modelBuilder.Entity("ExpertBridge.Core.Entities.User.User", b =>
                {
                    b.Navigation("Profile")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
