// <auto-generated />
using System;
using ExpertBridge.Data.DatabaseContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace ExpertBridge.Data.Migrations
{
    [DbContext(typeof(ExpertBridgeDbContext))]
    partial class ExpertBridgeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ExpertBridge.Core.Entities.Areas.Area", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("Governorate")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ProfileId")
                        .IsRequired()
                        .HasColumnType("character varying(450)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.ToTable("Areas");
                });

            modelBuilder.Entity("ExpertBridge.Core.Entities.Badges.Badge", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Badges");
                });

            modelBuilder.Entity("ExpertBridge.Core.Entities.Chats.Chat", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Chats");
                });

            modelBuilder.Entity("ExpertBridge.Core.Entities.CommentVotes.CommentVote", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("CommentId")
                        .IsRequired()
                        .HasColumnType("character varying(450)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsUpvote")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProfileId")
                        .IsRequired()
                        .HasColumnType("character varying(450)");

                    b.HasKey("Id");

                    b.HasIndex("CommentId");

                    b.HasIndex("ProfileId", "CommentId")
                        .IsUnique();

                    b.ToTable("CommentVotes");
                });

            modelBuilder.Entity("ExpertBridge.Core.Entities.Comments.Comment", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("AuthorId")
                        .IsRequired()
                        .HasColumnType("character varying(450)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsProcessed")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastModified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ParentCommentId")
                        .HasColumnType("character varying(450)");

                    b.Property<string>("PostId")
                        .IsRequired()
                        .HasColumnType("character varying(450)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("IsProcessed");

                    b.HasIndex("ParentCommentId");

                    b.HasIndex("PostId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("ExpertBridge.Core.Entities.JobApplication.JobApplication", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("AppliedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ContractorProfileId")
                        .IsRequired()
                        .HasColumnType("character varying(450)");

                    b.Property<string>("CoverLetter")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("JobPostingId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ContractorProfileId");

                    b.ToTable("JobApplications");
                });

            modelBuilder.Entity("ExpertBridge.Core.Entities.JobCategories.JobCategory", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("JobCategories");
                });

            modelBuilder.Entity("ExpertBridge.Core.Entities.JobPostings.JobPosting", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("AreaId")
                        .IsRequired()
                        .HasColumnType("character varying(450)");

                    b.Property<string>("AuthorId")
                        .IsRequired()
                        .HasColumnType("character varying(450)");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasColumnType("character varying(450)");

                    b.Property<double>("Cost")
                        .HasPrecision(18, 2)
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.HasIndex("AuthorId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Title");

                    b.ToTable("JobPostings");
                });

            modelBuilder.Entity("ExpertBridge.Core.Entities.JobReviews.JobReview", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("character varying(450)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("JobId")
                        .IsRequired()
                        .HasColumnType("character varying(450)");

                    b.Property<DateTime?>("LastModified")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<string>("WorkerId")
                        .IsRequired()
                        .HasColumnType("character varying(450)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("JobId")
                        .IsUnique();

                    b.HasIndex("WorkerId");

                    b.ToTable("JobReviews");
                });

            modelBuilder.Entity("ExpertBridge.Core.Entities.Jobs.Job", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<double>("ActualCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("double precision");

                    b.Property<string>("AuthorId")
                        .IsRequired()
                        .HasColumnType("character varying(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("JobPostingId")
                        .HasColumnType("character varying(450)");

                    b.Property<string>("ProfileId")
                        .HasColumnType("character varying(450)");

                    b.Property<string>("ProfileId1")
                        .HasColumnType("character varying(450)");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WorkerId")
                        .IsRequired()
                        .HasColumnType("character varying(450)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("JobPostingId")
                        .IsUnique();

                    b.HasIndex("ProfileId");

                    b.HasIndex("ProfileId1");

                    b.HasIndex("WorkerId");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("ExpertBridge.Core.Entities.ManyToManyRelationships.ChatParticipants.ChatParticipant", b =>
                {
                    b.Property<string>("ChatId")
                        .HasColumnType("character varying(450)");

                    b.Property<string>("ProfileId")
                        .HasColumnType("character varying(450)");

                    b.HasKey("ChatId", "ProfileId");

                    b.HasIndex("ProfileId")
                        .IsUnique();

                    b.ToTable("ChatParticipants");
                });

            modelBuilder.Entity("ExpertBridge.Core.Entities.ManyToManyRelationships.PostTags.PostTag", b =>
                {
                    b.Property<string>("PostId")
                        .HasColumnType("character varying(450)");

                    b.Property<string>("TagId")
                        .HasColumnType("character varying(450)");

                    b.HasKey("PostId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("PostTags");
                });

            modelBuilder.Entity("ExpertBridge.Core.Entities.ManyToManyRelationships.ProfileBadges.ProfileBadge", b =>
                {
                    b.Property<string>("ProfileId")
                        .HasColumnType("character varying(450)");

                    b.Property<string>("BadgeId")
                        .HasColumnType("character varying(450)");

                    b.HasKey("ProfileId", "BadgeId");

                    b.HasIndex("BadgeId");

                    b.ToTable("ProfileBadges");
                });

            modelBuilder.Entity("ExpertBridge.Core.Entities.ManyToManyRelationships.ProfileSkills.ProfileSkill", b =>
                {
                    b.Property<string>("ProfileId")
                        .HasColumnType("character varying(450)");

                    b.Property<string>("SkillId")
                        .HasColumnType("character varying(450)");

                    b.HasKey("ProfileId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("ProfileSkills");
                });

            modelBuilder.Entity("ExpertBridge.Core.Entities.ManyToManyRelationships.UserInterests.UserInterest", b =>
                {
                    b.Property<string>("ProfileId")
                        .HasColumnType("character varying(450)");

                    b.Property<string>("TagId")
                        .HasColumnType("character varying(450)");

                    b.HasKey("ProfileId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("UserInterests");
                });

            modelBuilder.Entity("ExpertBridge.Core.Entities.Media.ChatMedia.ChatMedia", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("ChatId")
                        .HasColumnType("character varying(450)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModified")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ChatId");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("ChatMedias");
                });

            modelBuilder.Entity("ExpertBridge.Core.Entities.Media.CommentMedia.CommentMedia", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("CommentId")
                        .HasColumnType("character varying(450)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModified")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CommentId");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("CommentMedias");
                });

            modelBuilder.Entity("ExpertBridge.Core.Entities.Media.JobPostingMedia.JobPostingMedia", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("JobPostingId")
                        .HasColumnType("character varying(450)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModified")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("JobPostingId");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("JobPostingMedias");
                });

            modelBuilder.Entity("ExpertBridge.Core.Entities.Media.MediaGrants.MediaGrant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ActivatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("GrantedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("OnHold")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("OnHold", "GrantedAt");

                    b.ToTable("MediaGrants");
                });

            modelBuilder.Entity("ExpertBridge.Core.Entities.Media.PostMedia.PostMedia", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModified")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PostId")
                        .HasColumnType("character varying(450)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.HasIndex("PostId");

                    b.ToTable("PostMedias");
                });

            modelBuilder.Entity("ExpertBridge.Core.Entities.Media.ProfileExperienceMedia.ProfileExperienceMedia", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModified")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ProfileExperienceId")
                        .HasColumnType("character varying(450)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.HasIndex("ProfileExperienceId");

                    b.ToTable("ProfileExperienceMedias");
                });

            modelBuilder.Entity("ExpertBridge.Core.Entities.Media.ProfileMedia.ProfileMedia", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModified")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ProfileId")
                        .HasColumnType("character varying(450)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.HasIndex("ProfileId");

                    b.ToTable("ProfileMedias");
                });

            modelBuilder.Entity("ExpertBridge.Core.Entities.ModerationReports.ModerationReport", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("AuthorId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("IdentityAttack")
                        .HasColumnType("double precision");

                    b.Property<double>("Insult")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsNegative")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Obscene")
                        .HasColumnType("double precision");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("SevereToxicity")
                        .HasColumnType("double precision");

                    b.Property<double>("SexualExplicit")
                        .HasColumnType("double precision");

                    b.Property<double>("Threat")
                        .HasColumnType("double precision");

                    b.Property<double>("Toxicity")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("ContentId");

                    b.HasIndex("IsNegative");

                    b.HasIndex("IsNegative", "ContentId");

                    b.ToTable("ModerationReports");
                });

            modelBuilder.Entity("ExpertBridge.Core.Entities.Notifications.Notification", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ActionUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IconActionUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("IconUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("RecipientId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("SenderId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("IsRead");

                    b.HasIndex("RecipientId");

                    b.HasIndex("IsRead", "CreatedAt");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("ExpertBridge.Core.Entities.PostVotes.PostVote", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsUpvote")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PostId")
                        .IsRequired()
                        .HasColumnType("character varying(450)");

                    b.Property<string>("ProfileId")
                        .IsRequired()
                        .HasColumnType("character varying(450)");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("ProfileId", "PostId")
                        .IsUnique();

                    b.ToTable("PostVotes");
                });

            modelBuilder.Entity("ExpertBridge.Core.Entities.Posts.Post", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("AuthorId")
                        .IsRequired()
                        .HasColumnType("character varying(450)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(1024)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsProcessed")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTagged")
                        .HasColumnType("boolean");

                    b.Property<string>("Language")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModified")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("Embedding");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Embedding"), "hnsw");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Embedding"), new[] { "vector_cosine_ops" });

                    b.HasIndex("IsProcessed");

                    b.HasIndex("IsTagged");

                    b.HasIndex("Title");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("ExpertBridge.Core.Entities.ProfileExperiences.ProfileExperience", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("EndDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ProfileId")
                        .IsRequired()
                        .HasColumnType("character varying(450)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.ToTable("ProfileExperiences");
                });

            modelBuilder.Entity("ExpertBridge.Core.Entities.Profiles.Profile", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("Bio")
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsBanned")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("JobTitle")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ProfilePictureUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<double>("Rating")
                        .HasColumnType("double precision");

                    b.Property<int>("RatingCount")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("character varying(450)");

                    b.Property<Vector>("UserInterestEmbedding")
                        .HasColumnType("vector(1024)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("(\"IsDeleted\") = false");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasFilter("(\"IsDeleted\") = false");

                    b.HasIndex("FirstName", "LastName")
                        .HasAnnotation("Npgsql:TsVectorConfig", "english");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("FirstName", "LastName"), "GIN");

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("ExpertBridge.Core.Entities.Skills.Skill", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("ExpertBridge.Core.Entities.Tags.Tag", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("ArabicName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("EnglishName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ArabicName")
                        .IsUnique();

                    b.HasIndex("EnglishName")
                        .IsUnique();

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("ExpertBridge.Core.Entities.Users.User", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsBanned")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOnboarded")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("(\"IsDeleted\") = false");

                    b.HasIndex("ProviderId")
                        .IsUnique()
                        .HasFilter("(\"IsDeleted\") = false");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasFilter("(\"IsDeleted\") = false");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ExpertBridge.Core.Entities.Areas.Area", b =>
                {
                    b.HasOne("ExpertBridge.Core.Entities.Profiles.Profile", "Profile")
                        .WithMany("Areas")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("ExpertBridge.Core.Entities.CommentVotes.CommentVote", b =>
                {
                    b.HasOne("ExpertBridge.Core.Entities.Comments.Comment", "Comment")
                        .WithMany("Votes")
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExpertBridge.Core.Entities.Profiles.Profile", "Profile")
                        .WithMany("CommentVotes")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comment");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("ExpertBridge.Core.Entities.Comments.Comment", b =>
                {
                    b.HasOne("ExpertBridge.Core.Entities.Profiles.Profile", "Author")
                        .WithMany("Comments")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExpertBridge.Core.Entities.Comments.Comment", "ParentComment")
                        .WithMany("Replies")
                        .HasForeignKey("ParentCommentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ExpertBridge.Core.Entities.Posts.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("ParentComment");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("ExpertBridge.Core.Entities.JobApplication.JobApplication", b =>
                {
                    b.HasOne("ExpertBridge.Core.Entities.Profiles.Profile", "ContractorProfile")
                        .WithMany()
                        .HasForeignKey("ContractorProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContractorProfile");
                });

            modelBuilder.Entity("ExpertBridge.Core.Entities.JobPostings.JobPosting", b =>
                {
                    b.HasOne("ExpertBridge.Core.Entities.Areas.Area", "Area")
                        .WithMany("JobPostings")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExpertBridge.Core.Entities.Profiles.Profile", "Author")
                        .WithMany("JobPostings")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExpertBridge.Core.Entities.JobCategories.JobCategory", "Category")
                        .WithMany("JobPostings")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");

                    b.Navigation("Author");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ExpertBridge.Core.Entities.JobReviews.JobReview", b =>
                {
                    b.HasOne("ExpertBridge.Core.Entities.Profiles.Profile", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExpertBridge.Core.Entities.Jobs.Job", "Job")
                        .WithOne("Review")
                        .HasForeignKey("ExpertBridge.Core.Entities.JobReviews.JobReview", "JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExpertBridge.Core.Entities.Profiles.Profile", "Worker")
                        .WithMany()
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Job");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("ExpertBridge.Core.Entities.Jobs.Job", b =>
                {
                    b.HasOne("ExpertBridge.Core.Entities.Profiles.Profile", "Author")
                        .WithMany("JobsAsAuthor")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExpertBridge.Core.Entities.JobPostings.JobPosting", "JobPosting")
                        .WithOne("Job")
                        .HasForeignKey("ExpertBridge.Core.Entities.Jobs.Job", "JobPostingId");

                    b.HasOne("ExpertBridge.Core.Entities.Profiles.Profile", null)
                        .WithMany("AuthoredJobs")
                        .HasForeignKey("ProfileId");

                    b.HasOne("ExpertBridge.Core.Entities.Profiles.Profile", null)
                        .WithMany("WorkedJobs")
                        .HasForeignKey("ProfileId1");

                    b.HasOne("ExpertBridge.Core.Entities.Profiles.Profile", "Worker")
                        .WithMany("JobsAsWorker")
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("JobPosting");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("ExpertBridge.Core.Entities.ManyToManyRelationships.ChatParticipants.ChatParticipant", b =>
                {
                    b.HasOne("ExpertBridge.Core.Entities.Chats.Chat", "Chat")
                        .WithMany("Participants")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExpertBridge.Core.Entities.Profiles.Profile", "Profile")
                        .WithOne("ChatParticipant")
                        .HasForeignKey("ExpertBridge.Core.Entities.ManyToManyRelationships.ChatParticipants.ChatParticipant", "ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chat");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("ExpertBridge.Core.Entities.ManyToManyRelationships.PostTags.PostTag", b =>
                {
                    b.HasOne("ExpertBridge.Core.Entities.Posts.Post", "Post")
                        .WithMany("PostTags")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExpertBridge.Core.Entities.Tags.Tag", "Tag")
                        .WithMany("PostTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("ExpertBridge.Core.Entities.ManyToManyRelationships.ProfileBadges.ProfileBadge", b =>
                {
                    b.HasOne("ExpertBridge.Core.Entities.Badges.Badge", "Badge")
                        .WithMany("ProfileBadges")
                        .HasForeignKey("BadgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExpertBridge.Core.Entities.Profiles.Profile", "Profile")
                        .WithMany("ProfileBadges")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Badge");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("ExpertBridge.Core.Entities.ManyToManyRelationships.ProfileSkills.ProfileSkill", b =>
                {
                    b.HasOne("ExpertBridge.Core.Entities.Profiles.Profile", "Profile")
                        .WithMany("ProfileSkills")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExpertBridge.Core.Entities.Skills.Skill", "Skill")
                        .WithMany("ProfileSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("ExpertBridge.Core.Entities.ManyToManyRelationships.UserInterests.UserInterest", b =>
                {
                    b.HasOne("ExpertBridge.Core.Entities.Profiles.Profile", "Profile")
                        .WithMany("ProfileTags")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExpertBridge.Core.Entities.Tags.Tag", "Tag")
                        .WithMany("ProfileTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("ExpertBridge.Core.Entities.Media.ChatMedia.ChatMedia", b =>
                {
                    b.HasOne("ExpertBridge.Core.Entities.Chats.Chat", "Chat")
                        .WithMany("Medias")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Chat");
                });

            modelBuilder.Entity("ExpertBridge.Core.Entities.Media.CommentMedia.CommentMedia", b =>
                {
                    b.HasOne("ExpertBridge.Core.Entities.Comments.Comment", "Comment")
                        .WithMany("Medias")
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Comment");
                });

            modelBuilder.Entity("ExpertBridge.Core.Entities.Media.JobPostingMedia.JobPostingMedia", b =>
                {
                    b.HasOne("ExpertBridge.Core.Entities.JobPostings.JobPosting", "JobPosting")
                        .WithMany("Medias")
                        .HasForeignKey("JobPostingId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("JobPosting");
                });

            modelBuilder.Entity("ExpertBridge.Core.Entities.Media.PostMedia.PostMedia", b =>
                {
                    b.HasOne("ExpertBridge.Core.Entities.Posts.Post", "Post")
                        .WithMany("Medias")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Post");
                });

            modelBuilder.Entity("ExpertBridge.Core.Entities.Media.ProfileExperienceMedia.ProfileExperienceMedia", b =>
                {
                    b.HasOne("ExpertBridge.Core.Entities.ProfileExperiences.ProfileExperience", "ProfileExperience")
                        .WithMany("Medias")
                        .HasForeignKey("ProfileExperienceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ProfileExperience");
                });

            modelBuilder.Entity("ExpertBridge.Core.Entities.Media.ProfileMedia.ProfileMedia", b =>
                {
                    b.HasOne("ExpertBridge.Core.Entities.Profiles.Profile", "Profile")
                        .WithMany("Medias")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("ExpertBridge.Core.Entities.PostVotes.PostVote", b =>
                {
                    b.HasOne("ExpertBridge.Core.Entities.Posts.Post", "Post")
                        .WithMany("Votes")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExpertBridge.Core.Entities.Profiles.Profile", "Profile")
                        .WithMany("PostVotes")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("ExpertBridge.Core.Entities.Posts.Post", b =>
                {
                    b.HasOne("ExpertBridge.Core.Entities.Profiles.Profile", "Author")
                        .WithMany("Posts")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("ExpertBridge.Core.Entities.ProfileExperiences.ProfileExperience", b =>
                {
                    b.HasOne("ExpertBridge.Core.Entities.Profiles.Profile", "Profile")
                        .WithMany("Experiences")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("ExpertBridge.Core.Entities.Profiles.Profile", b =>
                {
                    b.HasOne("ExpertBridge.Core.Entities.Users.User", "User")
                        .WithOne("Profile")
                        .HasForeignKey("ExpertBridge.Core.Entities.Profiles.Profile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ExpertBridge.Core.Entities.Areas.Area", b =>
                {
                    b.Navigation("JobPostings");
                });

            modelBuilder.Entity("ExpertBridge.Core.Entities.Badges.Badge", b =>
                {
                    b.Navigation("ProfileBadges");
                });

            modelBuilder.Entity("ExpertBridge.Core.Entities.Chats.Chat", b =>
                {
                    b.Navigation("Medias");

                    b.Navigation("Participants");
                });

            modelBuilder.Entity("ExpertBridge.Core.Entities.Comments.Comment", b =>
                {
                    b.Navigation("Medias");

                    b.Navigation("Replies");

                    b.Navigation("Votes");
                });

            modelBuilder.Entity("ExpertBridge.Core.Entities.JobCategories.JobCategory", b =>
                {
                    b.Navigation("JobPostings");
                });

            modelBuilder.Entity("ExpertBridge.Core.Entities.JobPostings.JobPosting", b =>
                {
                    b.Navigation("Job");

                    b.Navigation("Medias");
                });

            modelBuilder.Entity("ExpertBridge.Core.Entities.Jobs.Job", b =>
                {
                    b.Navigation("Review")
                        .IsRequired();
                });

            modelBuilder.Entity("ExpertBridge.Core.Entities.Posts.Post", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Medias");

                    b.Navigation("PostTags");

                    b.Navigation("Votes");
                });

            modelBuilder.Entity("ExpertBridge.Core.Entities.ProfileExperiences.ProfileExperience", b =>
                {
                    b.Navigation("Medias");
                });

            modelBuilder.Entity("ExpertBridge.Core.Entities.Profiles.Profile", b =>
                {
                    b.Navigation("Areas");

                    b.Navigation("AuthoredJobs");

                    b.Navigation("ChatParticipant")
                        .IsRequired();

                    b.Navigation("CommentVotes");

                    b.Navigation("Comments");

                    b.Navigation("Experiences");

                    b.Navigation("JobPostings");

                    b.Navigation("JobsAsAuthor");

                    b.Navigation("JobsAsWorker");

                    b.Navigation("Medias");

                    b.Navigation("PostVotes");

                    b.Navigation("Posts");

                    b.Navigation("ProfileBadges");

                    b.Navigation("ProfileSkills");

                    b.Navigation("ProfileTags");

                    b.Navigation("WorkedJobs");
                });

            modelBuilder.Entity("ExpertBridge.Core.Entities.Skills.Skill", b =>
                {
                    b.Navigation("ProfileSkills");
                });

            modelBuilder.Entity("ExpertBridge.Core.Entities.Tags.Tag", b =>
                {
                    b.Navigation("PostTags");

                    b.Navigation("ProfileTags");
                });

            modelBuilder.Entity("ExpertBridge.Core.Entities.Users.User", b =>
                {
                    b.Navigation("Profile")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
